<?php $_data = $this->getTableData(); ?>

<div class="grid">
    <table class="data" cellspacing="0">
        <thead>
            <tr class="headings">
                <th class="no-link"><span class="nobr"><?php echo Mage::helper('core')->__('Website Name') ?></span></th>
                <th class="no-link"><span class="nobr"><?php echo Mage::helper('catalogrule')->__('Catalog Price Rules') ?></span></th>
            </tr>
        </thead>
        <tbody
        <?php if (count($_data) > 0): ?>
        <?php foreach ($_data as $websiteData): ?>
        <tr>
            <td><?php echo $this->formatWebsiteName($websiteData['_object']) ?></td>
            <td>
                <div class="grid">
                    <table class="data" cellspacing="0">
                        <thead>
                            <tr class="headings">
                                <th class="no-link"><span class="nobr"><?php echo Mage::helper('catalogrule')->__('Rule Name') ?></span></th>
                                <th class="no-link"><span class="nobr"><?php echo Mage::helper('catalogrule')->__('Priority') ?></span></th>
                                <th class="no-link"><span class="nobr"><?php echo Mage::helper('catalogrule')->__('Stop Further Rules Processing') ?></span></th>
                                <th class="no-link"><span class="nobr"><?php echo Mage::helper('adminhtml')->__('Customer Groups') ?></span></th>
                                <th class="no-link"><span class="nobr"><?php echo Mage::helper('catalogrule')->__('Date Start') ?></span></th>
                                <th class="no-link"><span class="nobr"><?php echo Mage::helper('catalogrule')->__('Date Expire') ?></span></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($websiteData['_rules'] as $_rule): ?>
                            <tr>
                                <td><?php echo $this->formatRuleName($_rule['_object']) ?></td>
                                <td><?php echo $this->formatRulePriority($_rule['_object']) ?></td>
                                <td><?php echo $this->formatRuleStopProcessing($_rule['_object']) ?></td>
                                <td><?php echo $this->formatCustomerGroups($_rule['_object']) ?></td>
                                <td><?php echo $this->formatRuleDateStart($_rule['_object']) ?></td>
                                <td><?php echo $this->formatRuleDateExpire($_rule['_object']) ?></td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
        <?php endif; ?>
        <tbody>
    </table>
</div>